[package]
name = "black-raster"
version = "0.1.0"
authors = ["sinclairzx81 <haydn.developer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
black-math = { path = "../black-math" }